### ISSUE TITLE
Включается сглаживание шрифтов

### ISSUE THREAD

**Issue by zettx** [Sp1ker/vk_color_changer#6]
или что-то другое
![ee23ba2dbd 1](https://cloud.githubusercontent.com/assets/4026107/6626820/ba7d4212-c90a-11e4-9427-aec3b57f2738.jpg)

**Comment by Sp1ker** [comment]
Особенности -webkit-filter: hue-rotate(0deg);

**Comment by zettx** [comment]
параметр «Отключить DirectWrite Windows» на странице chrome://flags/ делает немного лучше.
